### PR TITLE
Strip abi version from libQt5Core

### LINKED ISSUE #37: Cannot run ozwdaemon docker image using older kernels, libQt5Core.so.5 not found
When I try to start ozwdaemon build 47 (and others) all I get is
```
/usr/local/bin/ozwdaemon: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory
```

For some reason, all other libraries are found so it does not appear to be that the linker doesn't look in the right folders, and `libQt5Core.so.5` does exist:
```
$ docker run --rm --entrypoint=/usr/bin/ldd docker.io/openzwave/ozwdaemon:latest /usr/local/bin/ozwdaemon
        linux-vdso.so.1 (0x00007ffc9f7e7000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f5ae8104000)
        libqt-openzwave.so.1 => /usr/local/lib/libqt-openzwave.so.1 (0x00007f5ae7fed000)
        libqt-openzwavedatabase.so.1 => /usr/local/lib/libqt-openzwavedatabase.so.1 (0x00007f5ae7fe6000)
        libunwind.so.8 => /usr/lib/x86_64-linux-gnu/libunwind.so.8 (0x00007f5ae7fc9000)
        libQt5Mqtt.so.5 => /usr/local/lib/libQt5Mqtt.so.5 (0x00007f5ae7f99000)
        libQt5Network.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Network.so.5 (0x00007f5ae7dde000)
        libQt5Core.so.5 => not found
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f5ae7dbb000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f5ae7c37000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5ae7a77000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f5ae81d4000)
        libopenzwave.so.1.6 => /usr/local/lib/libopenzwave.so.1.6 (0x00007f5ae78b5000)
        libQt5RemoteObjects.so.5 => /usr/lib/x86_64-linux-gnu/libQt5RemoteObjects.so.5 (0x00007f5ae7812000)
        libQt5Core.so.5 => not found
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f5ae77f6000)
        libQt5Core.so.5 => not found
        liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f5ae77ce000)
        libQt5Core.so.5 => not found
        libQt5Core.so.5 => not found
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f5ae75ae000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f5ae7469000)
        libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f5ae7451000)
        libQt5Core.so.5 => not found

$ docker run --rm --entrypoint=/bin/sh docker.io/openzwave/ozwdaemon:latest -c "/bin/ls -l /usr/lib/x86_64-linux-gnu/libQt*"
lrwxrwxrwx. 1 root root      20 Jan 30 21:03 /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 -> libQt5Core.so.5.12.5
lrwxrwxrwx. 1 root root      20 Jan 30 21:03 /usr/lib/x86_64-linux-gnu/libQt5Core.so.5.12 -> libQt5Core.so.5.12.5
-rw-r--r--. 1 root root 5454088 Jan 30 21:03 /usr/lib/x86_64-linux-gnu/libQt5Core.so.5.12.5
lrwxrwxrwx. 1 root root      20 Jan 30 21:03 /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5 -> libQt5DBus.so.5.12.5
lrwxrwxrwx. 1 root root      20 Jan 30 21:03 /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5.12 -> libQt5DBus.so.5.12.5
-rw-r--r--. 1 root root  619952 Jan 30 21:03 /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5.12.5
lrwxrwxrwx. 1 root root      23 Jan 30 21:03 /usr/lib/x86_64-linux-gnu/libQt5Network.so.5 -> libQt5Network.so.5.12.5
lrwxrwxrwx. 1 root root      23 Jan 30 21:03 /usr/lib/x86_64-linux-gnu/libQt5Network.so.5.12 -> libQt5Network.so.5.12.5
-rw-r--r--. 1 root root 1806136 Jan 30 21:03 /usr/lib/x86_64-linux-gnu/libQt5Network.so.5.12.5
lrwxrwxrwx. 1 root root      29 Dec 20 19:09 /usr/lib/x86_64-linux-gnu/libQt5RemoteObjects.so.5 -> libQt5RemoteObjects.so.5.12.5
lrwxrwxrwx. 1 root root      29 Dec 20 19:09 /usr/lib/x86_64-linux-gnu/libQt5RemoteObjects.so.5.12 -> libQt5RemoteObjects.so.5.12.5
-rw-r--r--. 1 root root  661680 Dec 20 19:09 /usr/lib/x86_64-linux-gnu/libQt5RemoteObjects.so.5.12.5
```

The host is running CentOS 7 / 7.7.1908, with the latest os-supplied docker (1.13.1 / 4ef4b30).

### PR DESCRIPTION
**Pull request by erikced**
Strip abi-version tag from `libQt5Core.so.5`, fixes #37.

### CODE REVIEW

**Comment by erikced** [comment]
Not going to work, path is arch-specific.

**Comment by Fishwaldo** [comment]
Wouldn't a 
```
strip --remove-section=.note.ABI-tag /usr/lib/*/libQt5Core.so.5
```
work?

**Comment by erikced** [comment]
> Wouldn't a
> 
> ```
> strip --remove-section=.note.ABI-tag /usr/lib/*/libQt5Core.so.5
> ```
> 
> work?

Yup, I just closed the broken PR until I had the time to fix it.

**Comment by Fishwaldo** [comment]
Thanks!

**Pull request merged**
